### ISSUE TITLE
/bin and /obj folder

### ISSUE THREAD

**Issue by josh-127** [veektorh/Forum#1]
Please remove the `/bin` and `/obj` folder. Generated files are considered bad practice. Usually, you want only the necessary files for building the project. Here's a [.gitignore](https://gitignore.io/api/linux,macos,csharp,windows,aspnetcore,visualstudio,visualstudiocode) template for C# and ASP.NET. With this, Git will automatically ignore generated files.

**Comment by veektorh** [comment]
Thanks the folders have been removed
